# Change these first
owner: leoherzog # Your GitHub organization or username, where this repository lives
repo: HopeStatus # The name of this repository

sites:
  - name: hope.edu
    url: https://hope.edu/
  - name: Spring 2023 Moodle
    url: https://courses202301.hope.edu/
  - name: Moodle Groups
    url: https://groups.hope.edu/
  - name: 1Hope Login
    url: https://sso.hope.edu/
  - name: PLUS Homepage
    url: https://plus.hope.edu/
  - name: PLUS Login
    url: https://prodbannersso.hope.edu/ssomanager/c/SSB
  - name: blogs.hope.edu
    url: https://blogs.hope.edu/
  - name: forms.hope.edu
    url: https://forms.hope.edu/
  - name: Course Schedule
    url: https://schedule.hope.edu/
  - name: Schedule Planner
    url: https://hope.collegescheduler.com/entry
  - name: Degree Works
    url: https://degreeworks.hope.edu/?as-student=true
  
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.herzog.tech
  # baseUrl: /your-repo-name
  theme: hope
  logoUrl: https://hope.edu/_resources/img/logo-color.svg
  name: Upptime Test
  introTitle: "[CIT](https://hope.edu/cit) continually monitors Hope systems."
  introMessage: "This tool is both an internal monitoring system for us, as well as a public statuspage to keep the Hope community in the know."
  navbar:
    - title: Status
      href: /
    - title: CIT Home
      href: https://hope.edu/cit

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
