blank_issues_enabled: true
issue_templates:
  - name: Scheduled Downtime
    template: scheduled_downtime.yml
    about: CIT employee scheduling an upcoming downtime
contact_links:
  - name: Something not working?
    url: mailto:cit@hope.edu
    about: Email the Help Desk at cit@hope.edu
